# Generated by Django 4.1.7 on 2023-04-05 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_Number', models.IntegerField()),
                ('street_Name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.address')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxPeople', models.IntegerField()),
                ('maxBed', models.IntegerField()),
                ('pricePerDay', models.FloatField()),
                ('campus_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hotelcampus')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Number', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('type_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_Duration', models.IntegerField()),
                ('cost', models.FloatField()),
                ('res_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
