# Generated by Django 4.2 on 2023-04-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_hotel_hotelamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_available',
            field=models.IntegerField(null=True),
        ),
    ]
