# Generated by Django 4.1.7 on 2023-04-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_address_hotelcampus_reservation_reserve_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('hotel_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelcampus',
            name='address_Id',
        ),
        migrations.RemoveField(
            model_name='reservationroom',
            name='res_Id',
        ),
        migrations.RemoveField(
            model_name='reservationroom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='campus_Id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_Price',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='point',
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_Number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type_Id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='travelers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.room'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='HotelCampus',
        ),
        migrations.DeleteModel(
            name='ReservationRoom',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='catalog.hotelamenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='catalog.roomamenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
