# Generated by Django 4.1.7 on 2023-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_hotel_hotelamenity_payment_roomamenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
