# Generated by Django 4.1.2 on 2023-05-01 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_roomamenity_room_reward_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="room",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="check_in",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="check_out",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 5, 13, 6, 472815)
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="reward",
            name="reward_points",
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name="reward",
            name="user",
            field=models.TextField(null=True),
        ),
    ]
