# Generated by Django 4.1.7 on 2023-04-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_hotel_email_remove_hotel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
