# Generated by Django 4.1.7 on 2023-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='state',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
