# Generated by Django 4.1.7 on 2023-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_hotel_city_remove_hotel_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_amenities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=models.TextField(null=True),
        ),
    ]
