# Generated by Django 4.1.7 on 2023-04-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_hotel_amenities_remove_room_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
