# Generated by Django 4.1.7 on 2023-04-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_reservation_hotel_room_check_in_room_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
