# Generated by Django 4.1.7 on 2023-04-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_room_check_in_remove_room_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
