# Generated by Django 4.1.7 on 2023-04-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_room_end_date_alter_room_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
    ]
