# Generated by Django 4.1.7 on 2023-04-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_room_price_per_night'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelAmenity',
        ),
        migrations.DeleteModel(
            name='RoomAmenity',
        ),
    ]
