# Generated by Django 4.1.7 on 2023-04-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_delete_hotelamenity_delete_roomamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_date',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.room')),
            ],
        ),
    ]
